#!/bin/bash

show() {
  ls -1 env
}

set() {
  printf "\nWORKSPACE = $1\n"

  filename=$1

  # Check if the file exists
  if [ -f "env/$filename" ]; then
    source env/$filename

    printf "\nGIT ENVIRONMENT\n\n"
    ./git/git-config.sh $git_username $git_email
  else
    echo "Environment does not exist :("
  fi
}

remove() {
  if [ -f "env/$1" ]; then
    rm env/$1
    echo "Environment $1 removed"
  else
    echo "Environment does not exist :("
  fi
}

config() {
  echo "Not implemented in this version!"
  # Source config REPL here
}

main() {
  case $1 in
  set)
    set $2
    ;;
  show)
    show
    ;;
  remove)
    remove $2
    ;;
  config)
    config
    ;;
  *)
    echo "Unknown command: $1"
    echo "Usage: $0 {show|set|config|remove} [arguments...]"
    ;;
  esac
}

main "$@"
